#!/usr/bin/env ruby

require "file_charset"
require "file_charset/cli.rb"


=begin
if ARGV.empty?
  STDOUT.puts "Usage: file_charset --encoding <encoding-name> [path, path, ...]"
  exit 1
end

if ARGV[0] == "--encoding"
  encoding = ARGV[1]
  paths = ARGV[2..-1]
else
  encoding = "UTF_8"
  paths = ARGV
end

exit FileCharset.check_paths_with_string_encoding(paths, encoding) ? 0 : 1
=end

CLI.start(ARGV)
